### ISSUE TITLE
several things

### ISSUE THREAD

**Issue by PystoyPlayer** [alt-art/TelegramBridge#16]
I tried to copy config from https://github.com/alt-art/TelegramBridge/blob/main/CONFIG.md (which seems to be outdated) but it reset to 
```
botToken: ...
chats:
- pinnedMessageId: 50509
  id: '...'
  thread: null
lang: ru
```
Also on plugin reload
![Shot (2024-06-07 at 12 19PM)@2x](https://github.com/alt-art/TelegramBridge/assets/88878911/ae78ae53-7917-412e-bc41-ad04031562f9)

And where's pinned message customization ? Don't see it anywhere and always get this one:
```
Hey welcome to the chat!
There are 0 players online
```

**Comment by PystoyPlayer** [comment]
hm now it broke after restart
![Shot (2024-06-07 at 12 29PM)@2x](https://github.com/alt-art/TelegramBridge/assets/88878911/3a14b2b5-760b-4b45-9d6d-0da25ced3151)
```
botToken: '00000000:123123123123123'
chats:
- pinnedMessageId: 50509
  id: '-100123123123'
  thread: null
lang: ru
```

**Comment by alt-art** [comment]
I am aware of those things, the `pinnedMessageId` now expect a string, but the config was setting the pinned Message to integer. I'm sorry for not working on these fixes early. You can get rid of this error by wrapping the value in quotes.

Also, the pinned message config is on the same file config.yml:

```
botToken: '00000000:123123123123123'
chats:
- pinnedMessageId: 50509
  id: '-100123123123'
  thread: null
lang: ru
pinned: "Message pinned"
```
