### ISSUE TITLE
Telegram messages are not sent in Minecraft

### ISSUE THREAD

**Issue by Fehrstix** [alt-art/TelegramBridge#26]
I'm getting an error in the logs, when a message from Telegram is attempted to be sent to Minecraft: https://mclo.gs/kO0K22d

**Comment by alt-art** [comment]
Can you provide the configuration file? With no token info of course.

**Comment by Fehrstix** [comment]
```
botToken: 
chats:
- pinnedMessageId: '58859'
  id: '-1002262445485'
  thread: '57361'
```
