### ISSUE TITLE
setpin issue

### ISSUE THREAD

**Issue by PystoyPlayer** [alt-art/TelegramBridge#8]
![Shot (2024-03-24 at 12 21PM)@2x](https://github.com/alt-art/TelegramBridge/assets/88878911/ce8ffd4e-1804-4c7d-8d89-334465a69fcc)
```
send_to_chat: true
send_to_telegram: true
log_join_and_leave_event: true
log_death_event: true
log_sleep_event: false
months: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь']
media_types: ['фото', 'видео', 'файл', 'аудио', 'голосовое', 'стикер', 'контакт', 'геолокацию', 'опрос', 'медиа']
messages:
  join: '%playername% присоединился к игре!'
  leave: '%playername% покинул игру!'
  death: '%playername% погиб! %deathmessage%'
  sleep: '%playername% лёг спать.'
  telegram: '[%playername%]: %message%'
  media: '§7[§bTelegram§7] §f[%user%] отправляет %type%.\n %caption%'
  chat: '§7[§bTelegram§7] §f[%user%] %message%'
  reply: '- §bОтвет §7%user% -\n'
  time: 'Время: %time% %emoji%\nДата: %month% %day%, %year% год'
  online: 'На сервере %count% игроков онлайн.\n%players%'
  pinned: 'IP: `subvost.mineserver.xyz`!\nИгроки онлайн (%count%):\n%players%\n\nСсылки: [Карта верхнего мира](http://185.186.143.152:26204/), [Discord](https://discord.gg/cWBv5wcE)'
```
